In [84]:
# Importación de librerías

import pandas as pd
import numpy as np

# Configuración para visualizar todas las columnas del DataFrame
pd.set_option('display.max_columns', None)

In [85]:
df_episodes = pd.read_csv("files/the_office_episodes.csv")

df_episodes.head()

,season,episode_num_in_season,episode_num_overall,title,directed_by,written_by,original_air_date,prod_code,us_viewers
0,1,1,1,Pilot,Ken Kwapis,Ricky Gervais & Stephen Merchant and Greg Daniels,2005-03-24,1001,11200000.0
1,1,2,2,Diversity Day,Ken Kwapis,B. J. Novak,2005-03-29,1002,6000000.0
2,1,3,3,Health Care,Ken Whittingham,Paul Lieberstein,2005-04-05,1006,5800000.0
3,1,4,4,The Alliance,Bryan Gordon,Michael Schur,2005-04-12,1004,5400000.0
4,1,5,5,Basketball,Greg Daniels,Greg Daniels,2005-04-19,1005,5000000.0

In [86]:
df_episodes.shape

(201, 9)

In [87]:
df_episodes.duplicated().sum()

np.int64(0)

In [88]:
df_episodes.isna().sum()

season                   0
episode_num_in_season    0
episode_num_overall      0
title                    0
directed_by              0
written_by               0
original_air_date        0
prod_code                0
us_viewers               0
dtype: int64

In [89]:
df_episodes.info()

<class 'pandas.DataFrame'>
RangeIndex: 201 entries, 0 to 200
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   season                 201 non-null    int64
 1   episode_num_in_season  201 non-null    int64
 2   episode_num_overall    201 non-null    int64
 3   title                  201 non-null    str
 4   directed_by            201 non-null    str
 5   written_by             201 non-null    str
 6   original_air_date      201 non-null    str
 7   prod_code              201 non-null    int64
 8   us_viewers             201 non-null    float64
dtypes: float64(1), int64(4), str(4)
memory usage: 14.3 KB

In [90]:
df_imdb = pd.read_csv("files/the_office_imdb.csv")

df_imdb.head()

,season,episode_num,title,original_air_date,imdb_rating,total_votes,desc
0,1,1,Pilot,2005-03-24,7.4,7006,The premiere episode introduces the boss and s...
1,1,2,Diversity Day,2005-03-29,8.3,6902,Michael's off color remark puts a sensitivity ...
2,1,3,Health Care,2005-04-05,7.7,5756,Michael leaves Dwight in charge of picking the...
3,1,4,The Alliance,2005-04-12,8.0,5579,"Just for a laugh, Jim agrees to an alliance wi..."
4,1,5,Basketball,2005-04-19,8.4,6183,Michael and his staff challenge the warehouse ...

In [91]:
df_imdb.shape

(188, 7)

In [92]:
df_imdb.duplicated().sum()

np.int64(0)

In [93]:
df_imdb.isna().sum()

season               0
episode_num          0
title                0
original_air_date    0
imdb_rating          0
total_votes          0
desc                 0
dtype: int64

In [94]:
df_imdb.info()

<class 'pandas.DataFrame'>
RangeIndex: 188 entries, 0 to 187
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   season             188 non-null    int64
 1   episode_num        188 non-null    int64
 2   title              188 non-null    str
 3   original_air_date  188 non-null    str
 4   imdb_rating        188 non-null    float64
 5   total_votes        188 non-null    int64
 6   desc               188 non-null    str
dtypes: float64(1), int64(3), str(3)
memory usage: 10.4 KB

In [95]:
df_series = pd.read_csv("files/the_office_series.csv", index_col=0)

df_series.head()

,Season,EpisodeTitle,About,Ratings,Votes,Viewership,Duration,Date,GuestStars,Director,Writers
0,1,Pilot,The premiere episode introduces the boss and s...,7.5,4936,11.2,23,24 March 2005,NaN,Ken Kwapis,Ricky Gervais |Stephen Merchant and Greg Daniels
1,1,Diversity Day,Michael's off color remark puts a sensitivity ...,8.3,4801,6.0,23,29 March 2005,NaN,Ken Kwapis,B. J. Novak
2,1,Health Care,Michael leaves Dwight in charge of picking the...,7.8,4024,5.8,22,5 April 2005,NaN,Ken Whittingham,Paul Lieberstein
3,1,The Alliance,"Just for a laugh, Jim agrees to an alliance wi...",8.1,3915,5.4,23,12 April 2005,NaN,Bryan Gordon,Michael Schur
4,1,Basketball,Michael and his staff challenge the warehouse ...,8.4,4294,5.0,23,19 April 2005,NaN,Greg Daniels,Greg Daniels

In [96]:
df_series.duplicated().sum()

np.int64(0)

In [97]:
df_series.isna().sum()/df_series.shape[0]*100

Season           0.000000
EpisodeTitle     0.000000
About            0.000000
Ratings          0.000000
Votes            0.000000
Viewership       0.000000
Duration         0.000000
Date             0.000000
GuestStars      84.574468
Director         0.000000
Writers          0.000000
dtype: float64

In [98]:
df_series.info()

<class 'pandas.DataFrame'>
RangeIndex: 188 entries, 0 to 187
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Season        188 non-null    int64
 1   EpisodeTitle  188 non-null    str
 2   About         188 non-null    str
 3   Ratings       188 non-null    float64
 4   Votes         188 non-null    int64
 5   Viewership    188 non-null    float64
 6   Duration      188 non-null    int64
 7   Date          188 non-null    str
 8   GuestStars    29 non-null     str
 9   Director      188 non-null    str
 10  Writers       188 non-null    str
dtypes: float64(2), int64(3), str(6)
memory usage: 16.3 KB

In [99]:
df_lines = pd.read_csv("files/the_office_lines.csv", index_col=0)

df_lines.head()

,Character,Line,Season,Episode_Number
0,Michael,All right Jim. Your quarterlies look very goo...,1,1
1,Jim,"Oh, I told you. I couldn’t close it. So…",1,1
2,Michael,So you’ve come to the master for guidance? Is...,1,1
3,Jim,"Actually, you called me in here, but yeah.",1,1
4,Michael,"All right. Well, let me show you how it’s don...",1,1

In [100]:
df_lines.shape

(58721, 4)

In [101]:
df_lines.duplicated().sum()

np.int64(649)

In [102]:
df_lines[df_lines.duplicated(keep=False)].value_counts()

Character  Line          Season  Episode_Number
Pam         Okay.        6       16                7
Dwight     What?         6       13                6
Holly      No.           7       18                6
Dwight     No.           7       22                6
Group      Yeah!         9       4                 6
                                                  ..
Dwight     Thank you.    9       21                2
Jim        Yeah.         9       22                2
Kevin      Whoa.         9       22                2
Casey      Oh.           9       22                2
Phillip    Mama.         9       22                2
Name: count, Length: 531, dtype: int64

In [103]:
df_lines.isna().sum()

Character         0
Line              0
Season            0
Episode_Number    0
dtype: int64

In [104]:
df_lines.info()

<class 'pandas.DataFrame'>
Index: 58721 entries, 0 to 61306
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Character       58721 non-null  str
 1   Line            58721 non-null  str
 2   Season          58721 non-null  int64
 3   Episode_Number  58721 non-null  int64
dtypes: int64(2), str(2)
memory usage: 2.2 MB

In [105]:
df_cameos = pd.read_csv("files/the_office_cameos.csv")

df_cameos.head()

,Temporada,Episodio,Artista,Personaje
0,4,13,Jack Black,Sam (en la película 'Mrs. Albert Hannaday')
1,4,13,Jessica Alba,Sophie (en la película 'Mrs. Albert Hannaday')
2,4,13,Cloris Leachman,Lily (en la película 'Mrs. Albert Hannaday')
3,7,14,Ricky Gervais,David Brent
4,7,17,Will Ferrell,Deangelo Vickers

In [106]:
df_cameos.shape

(20, 4)

In [107]:
df_cameos.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Temporada  20 non-null     int64
 1   Episodio   20 non-null     int64
 2   Artista    20 non-null     str
 3   Personaje  20 non-null     str
dtypes: int64(2), str(2)
memory usage: 772.0 bytes

In [108]:
df_scenario = pd.read_csv("files/the_office_scenario.csv")

df_scenario.head()

                             Escenario  Escenas_Aproximadas  Porcentaje
0       Oficina Principal (Open Space)                 4180        44.2
1  Despacho del Gerente (Michael/Andy)                 1400        14.8
2     Sala de Juntas (Conference Room)                 1115        11.8
3            Cocina / Zona de Descanso                  745         7.9
4                            Recepción                  560         5.9

In [109]:
df_scenario.shape

(9, 3)

In [110]:
df_scenario.info()

<class 'pandas.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 3 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Escenario            9 non-null      str
 1   Escenas_Aproximadas  9 non-null      int64
 2   Porcentaje           9 non-null      float64
dtypes: float64(1), int64(1), str(1)
memory usage: 348.0 bytes